[project]
name = "cockpit2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiocoap>=0.4.17",
    "cbor2>=5.8.0",
    "pycoreconf",
]

[tool.uv.sources]
pycoreconf = { git = "https://github.com/ltn22/pycoreconf.git", rev = "9a2134bffbd78c929b61f176d0ba3986069bb9a9" }
aiocoap = { git = "https://github.com/ltn22/aiocoap.git" }
